name: Release All OS - No Code Signing

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Draft Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.gh_release.outputs.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from input
        id: vars
        run: echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Extract changelog link
        id: changelog
        run: |
          VERSION=${{ steps.vars.outputs.version }}
          LINK="https://github.com/${{ github.repository }}/blob/${{ inputs.version }}/CHANGELOG.md#v${VERSION}"
          echo "link=$LINK" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          name: ${{ steps.vars.outputs.version }}
          draft: true
          prerelease: false
          body: |
            See the changes in [CHANGELOG.md](${{ steps.changelog.outputs.link }}).
