name: Tag on Merge of Prepare PR

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  tag-on-merge:
    if: |
      github.event.head_commit.message == 'chore: update CHANGELOG for ' || startsWith(github.event.head_commit.message, 'chore: prepare v')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract-version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ chore:\ prepare\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "version=v${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No valid prepare commit found."
            exit 1
          fi

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git tag ${{ steps.extract-version.outputs.version }}
          git push origin ${{ steps.extract-version.outputs.version }}

  create-release:
    needs: tag-on-merge
    uses: ./.github/workflows/create-release.yml
    with:
      version: ${{ needs.tag-on-merge.outputs.version }}
