name: Tag on Merge of Prepare PR

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  tag-on-merge:
    if: github.event.head_commit.message == 'chore: update CHANGELOG for ' || startsWith(github.event.head_commit.message, 'chore: prepare ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ chore:\ prepare\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "VERSION=v${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "No valid prepare commit found."
            exit 1
          fi

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git tag $VERSION
          git push origin $VERSION
